package by.vlad.fishingshop.controller.command;

public enum CommandType {
    GO_TO_START_PAGE_COMMAND,
    GO_TO_USERS_PAGE_COMMAND,
    GO_TO_LOGIN_PAGE_COMMAND,
    GO_TO_SIGN_UP_PAGE_COMMAND,
    GO_TO_EDIT_PRODUCT_PAGE_COMMAND,
    GO_TO_ACTIVATION_PAGE_COMMAND,
    GO_TO_MANAGER_PAGE,
    GO_TO_PRODUCT_PAGE,
    DEFAULT,
    START_PAGE_COMMAND,
    LOGIN_COMMAND,
    SIGN_UP_COMMAND,
    ACTIVATE_COMMAND,
    LOG_OUT_COMMAND,
    EDIT_NEW_PRODUCT_COMMAND,
    SET_TO_CART_COMMAND,
    CLEAR_CART_COMMAND,
    PURCHASE_COMMAND,
    GET_PRODUCTS_BY_TYPE_COMMAND,
    GO_TO_USER_ORDERS_PAGE_COMMAND,
    CHANGE_ORDER_STATUS_COMMAND,
    GET_ORDER_DATA_COMMAND,
    GO_TO_SEARCH_PRODUCT_BY_VENDOR_PAGE_COMMAND,
    GO_TO_SEARCH_PRODUCT_BY_NAME_PAGE_COMMAND,
    GO_TO_FORECAST_PAGE_COMMAND,
    SEARCH_PRODUCT_BY_PRODUCT_NAME_COMMAND,
    SEARCH_PRODUCT_BY_VENDOR_COMMAND,
    GET_PRODUCT_TO_UPDATE_COMMAND,
    UPDATE_PRODUCT_COMMAND,
    FIND_ORDERS_BY_STATUS_COMMAND,
    GO_TO_MANAGER_PAGE_COMMAND,
    GO_TO_EDIT_MANAGER_PAGE_COMMAND, EDIT_MANAGER_COMMAND, GO_TO_ADMIN_PAGE_COMMAND, CHANGE_USER_STATUS_COMMAND, GO_TO_SEARCH_USER_BY_LOGIN_COMMAND, SEARCH_USER_BY_LOGIN_COMMAND, CHANGE_LOCALE_COMMAND;


}
